version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/learning-ai-agents/google-adk)
      custom-order: true
      skip-generated: true

linters:
  enable:
    - misspell
    - revive
    - staticcheck
    - unused
  disable:
    - errcheck
  exclusions:
    rules:
    - path: "_test.go"
      text: "unused-parameter"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
